### ISSUE TITLE
General: Forum / Showcase / Github Page / Communication channels

### ISSUE THREAD

**Issue by twistedjoe** [crossbridge-community/crossbridge#43]
Hi,
I didn't know where to put this. 
We are heavily using the project on our open source game engine. Thanks for helping keeping the project alive. 

I have seen that there is a forum on the sourceforge page with a "issue reports" and a "Feature requests" topic. You can't create more. I think it would be helpful to have a place where you can post what your working on (crossbridge linux port for example), planed feature or showcase your project using it. The flascc forum is kind of dead and is more "Have an issue/get help" oriented.

I really don't want this project to die. Any idea on where we could keep the discussion going?

**Comment by twistedjoe** [comment]
I was working with a graphic designer for logos for a bunch of open source project I run. Do you think I should ask for a a crossbridge logo too or you prefer the one on github? If so I guess you don't have a vector version or a bigger one ?

I was trying to pimp the website a bit and I would like to put it somewhere.

**Comment by vpmedia** [comment]
Hi,
The current logo is made from a template and should be switched I think.
Thanks!

**Comment by twistedjoe** [comment]
I doubt I'll be able to make a bunch of revisions, else the designer will charge me a too much, but if we're not too picky it should be great.

**Comment by twistedjoe** [comment]
I installed a forum: http://forum.crossbridge.io
It will allow us to put some sticky topic. This way we can have, for example, a post that keep track of whats being worked on in the contribute category.

We can login with github, so no need to create an account.

@vpmedia just poke me if you want the admin rights.

**Comment by vpmedia** [comment]
Great, i've registered with a new account as vpmedia.

**Comment by twistedjoe** [comment]
You are admin now. 

I will forward new questions from the flascc forum to the new crossbridge forum.

 This way if adobe decide to kill  the old forum (since they don't maintain it) it won't take down all the questions and answer from this point. Which are valuable assets when developing.

**Comment by vpmedia** [comment]
Great, i've added the forum link to the sourceforge home page too.

**Comment by twistedjoe** [comment]
Added the logo on the staff section we can continue the discussion there.

I will also open an irc channel on freenode or somewhere and hang in there if people need help and I have free time.

Closing this topic.
