### ISSUE TITLE
Problem with compiling samples

### ISSUE THREAD

**Issue by arjrat** [crossbridge-community/crossbridge#74]
Hey, I hope this was the right place to post this as i was unable to find an active forum.

I was trying to compile the samples given with crossbridge and ended up getting the following errors:
![capture](https://cloud.githubusercontent.com/assets/10542483/5753083/86f7f914-9c37-11e4-8525-fadc996a9b08.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10542483/5753086/9130909e-9c37-11e4-91c7-cd36f0fdd0d8.JPG)

I made sure to reinstall crossbridge, cygwin and the required libraries (also tried using the cygwin installation given in the download). I also checked to ensure that java was installed and in the path.

There are no issues while trying to run my own make files with gcc and g++ on small c/c++ programs.
Thanks!

**Comment by twistedjoe** [comment]
Hi, the new active forum is : http://forum.crossbridge.io

Repost the same thing there + some info:
- which release are you using
- where does this release come from

Thanks!
