### ISSUE TITLE
After FP17 update, Neverball doesn't work, who knows what happened?

### ISSUE THREAD

**Issue by zy1691** [crossbridge-community/crossbridge#79]
After FP17 update, Pthread restored, very good!
However, neverball does not work, who knows what happened?

**Comment by vpmedia** [comment]
I've just tried it and it works for me..
http://vpmedia.hu/crossbridge/neverball
Are there any trace debug logs which you can post with the exception?

**Comment by zy1691** [comment]
My computer should be a problem,I'm sorry I did not do more tests.
 I reinstalled FP and ie,everything is normal,Although chrome still have this strange error.
I'm going to reinstall the system.
Thank you very much for your help.

**Comment by vpmedia** [comment]
Tip: maybe try to update Google Chrome browser which ships FP.
Also this document can help: https://helpx.adobe.com/flash-player/kb/flash-player-google-chrome.html
