### ISSUE TITLE
Accesing Win32 API from Crossbridge

### ISSUE THREAD

**Issue by pol2095** [crossbridge-community/crossbridge#88]
Hello,

I have to compile a C++ project using Crossbridge to create a swf. I am able to compile all the CPP files except those that uses Win32 API ("Windows.h"). I installed the api libraries on the cygwin folder but not on FlasCC sdk folder.

Thanks.

**Comment by rainbowcreatures** [comment]
That's not possible - if you want to work with Win32 API, you want to use AIR & native extensions (ANE's). Crossbridge compiles all the fancy C++ code into SWF for Flash Player, so even you can compile lots of C/C++ code you can't force Flash doing more than it can, like do stuff outside its sandbox.
