### ISSUE TITLE
Occasional slow down in Flash Player 18.0

### ISSUE THREAD

**Issue by rthorn** [crossbridge-community/crossbridge#89]
After recently updating my computer's Flash Player to 18.0 from 17, I began noticing that, every once in a while, code that had been compiled with Crossbridge ran unreasonably slow. It happens more frequently on lower quality computers; just about every time on a 2GB RAM Chromebook. This has been a problem in more than one project that uses Crossbridge.

**Comment by JoeDupuis** [comment]
I suspect a problem with the garbage collector. Can you inspect the memory usage with adobe scout? Try to see if the lag happen on memory usage drop.

**Comment by rthorn** [comment]
I have used Scout - the lag occurs every frame, and the ActionScript sampler says it's the methods run through Crossbridge that take many times longer than normal to run. There's not much garbage collecting going on, and memory usage is pretty normal.

**Comment by jasonsturges** [comment]
By chance, are these builds accessible to the public?  If so, could you provide a url?

**Comment by rthorn** [comment]
If it's helpful, here is a link to Scout flm files showing both normal and abnormal behavior, with advanced telemetry: https://github.com/rthorn/scratch-flash/tree/project-to-video/Adobe%20Scout
This is for a project that uses an open source flv encoder, which uses Alchemy (I've also had the problem with a very recent Crossbridge project). The encoder can be found here: https://github.com/zeropointnine/leelib

**Comment by rthorn** [comment]
Also, I am building swf files that target Flash Player 11.6.

**Comment by JoeDupuis** [comment]
Okay clearly not the garbage collector. 

Those two trace are the same tool exporting the same video for two different version of flash ?

FSM_makeImageBlocks.work (cmodule.flvEncodeHelper) seems to take WAY more time per frame in the abnormal file. It might be doing something that is slower in the new version of flash. The compiler has not changed in a while, so the outputed AS3 should be pretty much the same. I doubt it is related to the way crossbridge compile the function to AS3.

Inspecting the function and testing if any of the operation it does is abnormally long would be a starting point. 

The function does not seem to be doing much allocation either.  

Is the AbnormalCrossbridge.flm version compiled with the -O0 flag?

**Comment by JoeDupuis** [comment]
Just to be sure there is no optimization messing up the stack trace

**Comment by rthorn** [comment]
The traces are the same tool exporting the same video, both in the same version of flash, 18.0; the bug only happens occasionally, though I have no idea why that would be, as it's running exactly the same code. But I've never been able to reproduce this issue in earlier versions of flash player.

I don't compile with any -O_ flag.

**Comment by vpmedia** [comment]
Hi,
I've checked the Adobe AIR SDK release notes and I see:

```
Fixed Issues
August 11, 2015
Flash Player
Performance problems with Alchemy libraries [4020231]
```

> https://helpx.adobe.com/flash-player/release-note/fp_18_air_18_release_notes.html

So maybe try to update your Flash Player and re-test it.

**Comment by rthorn** [comment]
Thank you, with this latest update I can no longer reproduce the issue. Apologies for not checking that myself.
