### ISSUE TITLE
Crossbridge's uname in .../sdk/usr/bin/ always thinks it is on FreeBSD

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [crossbridge-community/crossbridge#93]
The executables in `crossbridge/sdk/usr/bin`, in particular uname, seem to be tailored towards a build environment of FreeBSD. IE: Running crossbridge's uname to see what platform the machine is running always returns "FreeBSD", regardless of the base system platform.

Then, in the case that the above `crossbridge/sdk/usr/bin` path is included in $PATH before everything (to allow for streamlined compilation using the crossbridge compiling tools), the system's uname is overridden. Then, any cross-platform scripts that rely on uname for platform-specific operations will be tricked and build for the wrong platform.

Is there any specific reason for this FreeBSD uname in crossbridge? Renaming this uname so that it cannot be found and the system uses its uname does not seem to cause any harm in building with crossbridge.

**Comment by JoeDupuis** [comment]
Crossbridge is an abstraction layer that mimic/emulate a FreeBSD environment over flash. If we remove uname or change its behaviour, configuration scripts and makefiles that rely on it to adapt the code to a freebsd-like environment (preprocessor) will fail.

I think that the solution here is to adapt your build script so it put the crossbridge bin folder in the path only for the build step where it is required (with a subshell for example).

**Comment by JoeDupuis** [comment]
It seems that not all the crosscompilers have the uname bin (android cross compiler does not), but it seems to be standard practice not to use it to get info about the host when cross compiling.

https://lists.gnupg.org/pipermail/gnupg-devel/2004-August/021219.html

You could still rename it on your side as a quick hack/fix if your build system is too complicated.
